package common.src.main.Server;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;

/**
 *   Util class that is responsible for storing all possible words and selecting three random when prompted.
 */

public class WordUtil {

    private static String words[] = {"delay",
            "vehicle",
            "rainbow",
            "pasta",
            "couch",
            "trophy",
            "elbow",
            "doorbell",
            "hairline",
            "showercap",
            "scarf",
            "calculator",
            "gnome",
            "STONKS",
            "eyelash",
            "maze",
            "field",
            "kiss",
            "pacifier",
            "auction",
            "fire",
            "hurt",
            "trance",
            "solve",
            "night",
            "wrestle",
            "debt",
            "mood",
            "duke",
            "drown",
            "button",
            "slap",
            "concern",
            "thaw",
            "lake",
            "disco",
            "bother",
            "route",
            "bank",
            "crash",
            "shelter",
            "sock",
            "tiptoe",
            "fall",
            "weight",
            "ritual",
            "pupil",
            "herd",
            "rebel",
            "whisper",
            "record",
            "note",
            "branch",
            "butter",
            "mark",
            "ghost",
            "side",
            "class",
            "stage",
            "kittens",
            "nation",
            "ink",
            "veil",
            "temper",
            "smash",
            "grain",
            "throat",
            "cake",
            "price",
            "cub",
            "walk",
            "expert",
            "partner",
            "angle",
            "trip",
            "coat",
            "pig",
            "reward",
            "knot",
            "finger",
            "touch",
            "teaching",
            "thumb",
            "stove",
            "brick",
            "shake",
            "night",
            "cover",
            "pets",
            "friction",
            "feeling",
            "person",
            "friend",
            "babies",
            "change",
            "industry",
            "quicksand",
            "scene",
            "blood",
            "berry",
            "stamp",
            "grass",
            "rabbits",
            "oil",
            "hat",
            "year",
            "push",
            "activity",
            "twig",
            "crib",
            "party",
            "pigs",
            "dolls",
            "yak",
            "nut",
            "stem",
            "story",
            "writing",
            "toothbrush",
            "camp",
            "zipper",
            "ants",
            "dust",
            "gun",
            "metal",
            "playground",
            "spoon",
            "soup",
            "cloth",
            "door",
            "reading",
            "insect",
            "birthday",
            "curtain",
            "crowd",
            "letters",
            "protest",
            "slave",
            "shame",
            "adjustment",
            "line",
            "driving",
            "mask",
            "animal",
            "minister",
            "snakes"};

    public static String[] generateWords() {
        Random rand = new Random();
        String res[] = new String[3];
        ArrayList<Integer> ints = new ArrayList<>();
        while (ints.size() < 3) {
            int newInt = rand.nextInt(words.length);
            if (!ints.contains(newInt)) {
                ints.add(newInt);
            }
        }

        for (int i = 0; i < 3; i++) {
            res[i] = words[ints.get(i)];
        }

        return res;
    }


}
